// Code generated by "so test". DO NOT EDIT.

package main

import "solod.dev/so/testing"

func main() {
	testing.RunTests("so/io", []testing.Test{
		{Name: "TestCopy", F: TestCopy},
		{Name: "TestCopyN", F: TestCopyN},
		{Name: "TestReadAll", F: TestReadAll},
		{Name: "TestReadFull", F: TestReadFull},
		{Name: "TestWriteString", F: TestWriteString},
		{Name: "TestLimitReader", F: TestLimitReader},
	})
}
