// Code generated by "so test". DO NOT EDIT.

package main

import "solod.dev/so/testing"

func main() {
	testing.RunTests("so/uuid", []testing.Test{
		{Name: "TestNew", F: TestNew},
		{Name: "TestStringParse", F: TestStringParse},
		{Name: "TestCompare", F: TestCompare},
	})
}
