// Code generated by "so test". DO NOT EDIT.

package main

import "solod.dev/so/testing"

func main() {
	testing.RunTests("so/unsafe", []testing.Test{
		{Name: "TestSizeof", F: TestSizeof},
		{Name: "TestAlignof", F: TestAlignof},
		{Name: "TestString", F: TestString},
		{Name: "TestStringData", F: TestStringData},
		{Name: "TestSlice", F: TestSlice},
		{Name: "TestSliceData", F: TestSliceData},
		{Name: "TestPointer", F: TestPointer},
	})
}
